apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: vuln-bank
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-bank-web
  namespace: vuln-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuln-bank-web
  template:
    metadata:
      labels:
        app: vuln-bank-web
    spec:
      containers:
        - name: web
          image: vulnbank-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "5432"
          volumeMounts:
            - name: uploads
              mountPath: /app/static/uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: vuln-bank-web
  namespace: vuln-bank
spec:
  type: LoadBalancer
  selector:
    app: vuln-bank-web
  ports:
    - name: http
      port: 80
      targetPort: 5000
